// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/dch/app/calc/CalcProtocol.proto

package com.dch.app.calc.netty;

import com.google.protobuf.AbstractMessage;

public final class CalcProtocol {
  private CalcProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.dch.app.calc.CalcOperation}
   */
  public enum CalcOperation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MULTIPLY = 1;</code>
     */
    MULTIPLY(0, 1),
    /**
     * <code>DIVIDE = 2;</code>
     */
    DIVIDE(1, 2),
    /**
     * <code>ADD = 3;</code>
     */
    ADD(2, 3),
    /**
     * <code>SUBSTRUCT = 4;</code>
     */
    SUBSTRUCT(3, 4),
    /**
     * <code>SET_VALUE = 5;</code>
     */
    SET_VALUE(4, 5),
    /**
     * <code>GET_VALUE = 6;</code>
     */
    GET_VALUE(5, 6),
    ;

    /**
     * <code>MULTIPLY = 1;</code>
     */
    public static final int MULTIPLY_VALUE = 1;
    /**
     * <code>DIVIDE = 2;</code>
     */
    public static final int DIVIDE_VALUE = 2;
    /**
     * <code>ADD = 3;</code>
     */
    public static final int ADD_VALUE = 3;
    /**
     * <code>SUBSTRUCT = 4;</code>
     */
    public static final int SUBSTRUCT_VALUE = 4;
    /**
     * <code>SET_VALUE = 5;</code>
     */
    public static final int SET_VALUE_VALUE = 5;
    /**
     * <code>GET_VALUE = 6;</code>
     */
    public static final int GET_VALUE_VALUE = 6;


    public final int getNumber() { return value; }

    public static CalcOperation valueOf(int value) {
      switch (value) {
        case 1: return MULTIPLY;
        case 2: return DIVIDE;
        case 3: return ADD;
        case 4: return SUBSTRUCT;
        case 5: return SET_VALUE;
        case 6: return GET_VALUE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CalcOperation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CalcOperation>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CalcOperation>() {
            public CalcOperation findValueByNumber(int number) {
              return CalcOperation.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CalcProtocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final CalcOperation[] VALUES = values();

    public static CalcOperation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CalcOperation(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.dch.app.calc.CalcOperation)
  }

  public interface CalcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dch.app.calc.CalcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 clientId = 1;</code>
     */
    boolean hasClientId();
    /**
     * <code>optional int64 clientId = 1;</code>
     */
    long getClientId();

    /**
     * <code>optional int64 number = 2;</code>
     */
    boolean hasNumber();
    /**
     * <code>optional int64 number = 2;</code>
     */
    long getNumber();

    /**
     * <code>required .com.dch.app.calc.CalcOperation operation = 3;</code>
     */
    boolean hasOperation();
    /**
     * <code>required .com.dch.app.calc.CalcOperation operation = 3;</code>
     */
    CalcProtocol.CalcOperation getOperation();
  }
  /**
   * Protobuf type {@code com.dch.app.calc.CalcRequest}
   */
  public static final class CalcRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.dch.app.calc.CalcRequest)
      CalcRequestOrBuilder {
    // Use CalcRequest.newBuilder() to construct.
    private CalcRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CalcRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CalcRequest defaultInstance;
    public static CalcRequest getDefaultInstance() {
      return defaultInstance;
    }

    public CalcRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CalcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              clientId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              number_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              CalcProtocol.CalcOperation value = CalcProtocol.CalcOperation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                operation_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CalcProtocol.internal_static_com_dch_app_calc_CalcRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CalcProtocol.internal_static_com_dch_app_calc_CalcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CalcProtocol.CalcRequest.class, CalcProtocol.CalcRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<CalcRequest> PARSER =
        new com.google.protobuf.AbstractParser<CalcRequest>() {
      public CalcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalcRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CalcRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CLIENTID_FIELD_NUMBER = 1;
    private long clientId_;
    /**
     * <code>optional int64 clientId = 1;</code>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 clientId = 1;</code>
     */
    public long getClientId() {
      return clientId_;
    }

    public static final int NUMBER_FIELD_NUMBER = 2;
    private long number_;
    /**
     * <code>optional int64 number = 2;</code>
     */
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 number = 2;</code>
     */
    public long getNumber() {
      return number_;
    }

    public static final int OPERATION_FIELD_NUMBER = 3;
    private CalcProtocol.CalcOperation operation_;
    /**
     * <code>required .com.dch.app.calc.CalcOperation operation = 3;</code>
     */
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .com.dch.app.calc.CalcOperation operation = 3;</code>
     */
    public CalcProtocol.CalcOperation getOperation() {
      return operation_;
    }

    private void initFields() {
      clientId_ = 0L;
      number_ = 0L;
      operation_ = CalcProtocol.CalcOperation.MULTIPLY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOperation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, clientId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, number_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, operation_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clientId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, number_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, operation_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CalcProtocol.CalcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CalcProtocol.CalcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CalcProtocol.CalcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CalcProtocol.CalcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CalcProtocol.CalcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CalcProtocol.CalcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CalcProtocol.CalcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CalcProtocol.CalcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CalcProtocol.CalcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CalcProtocol.CalcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CalcProtocol.CalcRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dch.app.calc.CalcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dch.app.calc.CalcRequest)
        CalcProtocol.CalcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CalcProtocol.internal_static_com_dch_app_calc_CalcRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CalcProtocol.internal_static_com_dch_app_calc_CalcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CalcProtocol.CalcRequest.class, CalcProtocol.CalcRequest.Builder.class);
      }

      // Construct using com.dch.app.calc.CalcProtocol.CalcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clientId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        number_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        operation_ = CalcProtocol.CalcOperation.MULTIPLY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CalcProtocol.internal_static_com_dch_app_calc_CalcRequest_descriptor;
      }

      public CalcProtocol.CalcRequest getDefaultInstanceForType() {
        return CalcProtocol.CalcRequest.getDefaultInstance();
      }

      public CalcProtocol.CalcRequest build() {
        CalcProtocol.CalcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public CalcProtocol.CalcRequest buildPartial() {
        CalcProtocol.CalcRequest result = new CalcProtocol.CalcRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.number_ = number_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.operation_ = operation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CalcProtocol.CalcRequest) {
          return mergeFrom((CalcProtocol.CalcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CalcProtocol.CalcRequest other) {
        if (other == CalcProtocol.CalcRequest.getDefaultInstance()) return this;
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasNumber()) {
          setNumber(other.getNumber());
        }
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOperation()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CalcProtocol.CalcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CalcProtocol.CalcRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long clientId_ ;
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public long getClientId() {
        return clientId_;
      }
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public Builder setClientId(long value) {
        bitField0_ |= 0x00000001;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = 0L;
        onChanged();
        return this;
      }

      private long number_ ;
      /**
       * <code>optional int64 number = 2;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 number = 2;</code>
       */
      public long getNumber() {
        return number_;
      }
      /**
       * <code>optional int64 number = 2;</code>
       */
      public Builder setNumber(long value) {
        bitField0_ |= 0x00000002;
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 number = 2;</code>
       */
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        number_ = 0L;
        onChanged();
        return this;
      }

      private CalcProtocol.CalcOperation operation_ = CalcProtocol.CalcOperation.MULTIPLY;
      /**
       * <code>required .com.dch.app.calc.CalcOperation operation = 3;</code>
       */
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .com.dch.app.calc.CalcOperation operation = 3;</code>
       */
      public CalcProtocol.CalcOperation getOperation() {
        return operation_;
      }
      /**
       * <code>required .com.dch.app.calc.CalcOperation operation = 3;</code>
       */
      public Builder setOperation(CalcProtocol.CalcOperation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.dch.app.calc.CalcOperation operation = 3;</code>
       */
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        operation_ = CalcProtocol.CalcOperation.MULTIPLY;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.dch.app.calc.CalcRequest)
    }

    static {
      defaultInstance = new CalcRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.dch.app.calc.CalcRequest)
  }

  public interface CalcResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dch.app.calc.CalcResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 clientId = 1;</code>
     */
    boolean hasClientId();
    /**
     * <code>optional int64 clientId = 1;</code>
     */
    long getClientId();

    /**
     * <code>optional int64 number = 2;</code>
     */
    boolean hasNumber();
    /**
     * <code>optional int64 number = 2;</code>
     */
    long getNumber();

    /**
     * <code>optional string error = 3;</code>
     */
    boolean hasError();
    /**
     * <code>optional string error = 3;</code>
     */
    java.lang.String getError();
    /**
     * <code>optional string error = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code com.dch.app.calc.CalcResponse}
   */
  public static final class CalcResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.dch.app.calc.CalcResponse)
      CalcResponseOrBuilder {
    // Use CalcResponse.newBuilder() to construct.
    private CalcResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CalcResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CalcResponse defaultInstance;
    public static CalcResponse getDefaultInstance() {
      return defaultInstance;
    }

    public CalcResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CalcResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              clientId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              number_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              error_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CalcProtocol.internal_static_com_dch_app_calc_CalcResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CalcProtocol.internal_static_com_dch_app_calc_CalcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CalcProtocol.CalcResponse.class, CalcProtocol.CalcResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<CalcResponse> PARSER =
        new com.google.protobuf.AbstractParser<CalcResponse>() {
      public CalcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalcResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CalcResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CLIENTID_FIELD_NUMBER = 1;
    private long clientId_;
    /**
     * <code>optional int64 clientId = 1;</code>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 clientId = 1;</code>
     */
    public long getClientId() {
      return clientId_;
    }

    public static final int NUMBER_FIELD_NUMBER = 2;
    private long number_;
    /**
     * <code>optional int64 number = 2;</code>
     */
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 number = 2;</code>
     */
    public long getNumber() {
      return number_;
    }

    public static final int ERROR_FIELD_NUMBER = 3;
    private java.lang.Object error_;
    /**
     * <code>optional string error = 3;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string error = 3;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          error_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      clientId_ = 0L;
      number_ = 0L;
      error_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, clientId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, number_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrorBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clientId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, number_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrorBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CalcProtocol.CalcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CalcProtocol.CalcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CalcProtocol.CalcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CalcProtocol.CalcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CalcProtocol.CalcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CalcProtocol.CalcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CalcProtocol.CalcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CalcProtocol.CalcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CalcProtocol.CalcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CalcProtocol.CalcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CalcProtocol.CalcResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dch.app.calc.CalcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dch.app.calc.CalcResponse)
        CalcProtocol.CalcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CalcProtocol.internal_static_com_dch_app_calc_CalcResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CalcProtocol.internal_static_com_dch_app_calc_CalcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CalcProtocol.CalcResponse.class, CalcProtocol.CalcResponse.Builder.class);
      }

      // Construct using com.dch.app.calc.CalcProtocol.CalcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clientId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        number_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CalcProtocol.internal_static_com_dch_app_calc_CalcResponse_descriptor;
      }

      public CalcProtocol.CalcResponse getDefaultInstanceForType() {
        return CalcProtocol.CalcResponse.getDefaultInstance();
      }

      public CalcProtocol.CalcResponse build() {
        CalcProtocol.CalcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public CalcProtocol.CalcResponse buildPartial() {
        CalcProtocol.CalcResponse result = new CalcProtocol.CalcResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.number_ = number_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.error_ = error_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CalcProtocol.CalcResponse) {
          return mergeFrom((CalcProtocol.CalcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CalcProtocol.CalcResponse other) {
        if (other == CalcProtocol.CalcResponse.getDefaultInstance()) return this;
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasNumber()) {
          setNumber(other.getNumber());
        }
        if (other.hasError()) {
          bitField0_ |= 0x00000004;
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CalcProtocol.CalcResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CalcProtocol.CalcResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long clientId_ ;
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public long getClientId() {
        return clientId_;
      }
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public Builder setClientId(long value) {
        bitField0_ |= 0x00000001;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = 0L;
        onChanged();
        return this;
      }

      private long number_ ;
      /**
       * <code>optional int64 number = 2;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 number = 2;</code>
       */
      public long getNumber() {
        return number_;
      }
      /**
       * <code>optional int64 number = 2;</code>
       */
      public Builder setNumber(long value) {
        bitField0_ |= 0x00000002;
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 number = 2;</code>
       */
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        number_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>optional string error = 3;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            error_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000004);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        error_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.dch.app.calc.CalcResponse)
    }

    static {
      defaultInstance = new CalcResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.dch.app.calc.CalcResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dch_app_calc_CalcRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dch_app_calc_CalcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dch_app_calc_CalcResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dch_app_calc_CalcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1src/main/java/com/dch/app/calc/CalcPro" +
      "tocol.proto\022\020com.dch.app.calc\"c\n\013CalcReq" +
      "uest\022\020\n\010clientId\030\001 \001(\003\022\016\n\006number\030\002 \001(\003\0222" +
      "\n\toperation\030\003 \002(\0162\037.com.dch.app.calc.Cal" +
      "cOperation\"?\n\014CalcResponse\022\020\n\010clientId\030\001" +
      " \001(\003\022\016\n\006number\030\002 \001(\003\022\r\n\005error\030\003 \001(\t*_\n\rC" +
      "alcOperation\022\014\n\010MULTIPLY\020\001\022\n\n\006DIVIDE\020\002\022\007" +
      "\n\003ADD\020\003\022\r\n\tSUBSTRUCT\020\004\022\r\n\tSET_VALUE\020\005\022\r\n" +
      "\tGET_VALUE\020\006"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_dch_app_calc_CalcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dch_app_calc_CalcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_dch_app_calc_CalcRequest_descriptor,
        new java.lang.String[] { "ClientId", "Number", "Operation", });
    internal_static_com_dch_app_calc_CalcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_dch_app_calc_CalcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_dch_app_calc_CalcResponse_descriptor,
        new java.lang.String[] { "ClientId", "Number", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
